from __future__ import annotations


DEFAULT_CATALOG_VERSION = "seed-20260419-v1"


DEFAULT_PRODUCT_CATALOG: list[dict] = [
    {
        "role_type": "primary",
        "family": "同步电机软起动",
        "series_name": "LCI 同步电机变频软起动系统",
        "code": "lci_sync_drive",
        "vendor": "标准产品",
        "description": "适用于高压同步电机的大功率软起动、同步切换和工频旁路场景。",
        "voltage_levels": ["6kV", "10kV"],
        "min_power_kw": 2000,
        "max_power_kw": 20000,
        "topology": "负载换流型",
        "applicable_motors": ["同步电机"],
        "applicable_loads": ["鼓风机", "压缩机", "磨机"],
        "communication_protocols": ["Profibus-DP", "Profinet", "Modbus TCP"],
        "io_allocation": {"DI": 16, "DO": 8, "AI": 4, "AO": 2},
        "protection_features": ["过流", "过压", "欠压", "同步失败", "过温"],
        "preferred_scenarios": ["同步切换", "工频旁路", "大惯量启动"],
        "default_chapters": [
            "总体方案",
            "主回路方案",
            "启动与同步切换控制",
            "DCS 通讯接口方案",
            "保护联锁方案",
            "主要设备技术参数",
            "供货范围与配置清单",
            "调试与验收",
        ],
        "standard_configs": [
            {
                "config_name": "标准配置",
                "components": [
                    {"role": "整流变压器", "series_code": "rectifier_transformer", "quantity": 1, "config": "标准配置"},
                    {"role": "励磁控制柜", "series_code": "excitation_cabinet", "quantity": 1, "config": "同步电机配套"},
                ],
                "applicable_scenarios": ["同步电机软起动"],
                "description": "包含整流变压器和励磁控制的标准主驱动配置。",
            },
            {
                "config_name": "旁路配置",
                "components": [
                    {"role": "整流变压器", "series_code": "rectifier_transformer", "quantity": 1, "config": "标准配置"},
                    {"role": "励磁控制柜", "series_code": "excitation_cabinet", "quantity": 1, "config": "同步电机配套"},
                    {"role": "旁路柜", "series_code": "bypass_cabinet", "quantity": 1, "config": "旁路配置"},
                ],
                "applicable_scenarios": ["工频旁路运行", "不停机检修", "同步切换"],
                "description": "带工频旁路切换的完整主驱动配置。",
            },
        ],
        "constraints": [
            {"constraint_type": "electrical", "condition": "同步电机", "action": "必须配套励磁控制柜。", "severity": "blocking"},
            {"constraint_type": "control", "condition": "要求工频旁路或不停机切换", "action": "应选用旁路配置并明确切换闭锁逻辑。", "severity": "warning"},
            {"constraint_type": "environmental", "condition": "海拔 > 1000m", "action": "需校核降额和散热条件。", "severity": "warning"},
        ],
    },
    {
        "role_type": "primary",
        "family": "高压变频",
        "series_name": "高压变频器多电平驱动系统",
        "code": "hv_vfd_multilevel",
        "vendor": "标准产品",
        "description": "适用于风机、泵、输送机等高压调速改造场景。",
        "voltage_levels": ["3.3kV", "6kV", "10kV"],
        "min_power_kw": 200,
        "max_power_kw": 8000,
        "topology": "单元串联多电平",
        "applicable_motors": ["异步电机", "同步电机"],
        "applicable_loads": ["风机", "泵", "输送机", "压缩机"],
        "communication_protocols": ["Profibus-DP", "Profinet", "Modbus TCP", "IEC 61850"],
        "io_allocation": {"DI": 16, "DO": 8, "AI": 4, "AO": 2},
        "protection_features": ["过流", "过压", "欠压", "单元故障", "接地故障"],
        "preferred_scenarios": ["节能调速", "风机", "泵"],
        "default_chapters": [
            "总体方案",
            "主回路方案",
            "控制系统方案",
            "DCS 通讯接口方案",
            "保护与联锁",
            "主要设备技术参数",
            "供货范围与配置清单",
            "安装调试要求",
        ],
        "standard_configs": [
            {
                "config_name": "标准配置",
                "components": [],
                "applicable_scenarios": ["一般节能调速"],
                "description": "标准高压变频系统配置。",
            },
            {
                "config_name": "旁路配置",
                "components": [
                    {"role": "旁路柜", "series_code": "bypass_cabinet", "quantity": 1, "config": "旁路配置"},
                ],
                "applicable_scenarios": ["要求工频旁路运行", "检修不停机"],
                "description": "带旁路切换的高压变频配置。",
            },
        ],
        "constraints": [
            {"constraint_type": "electrical", "condition": "电机电缆 > 100m", "action": "建议校核输出滤波和 dv/dt 抑制。", "severity": "warning"},
            {"constraint_type": "environmental", "condition": "环温 > 40°C", "action": "需校核降额或追加空调散热。", "severity": "warning"},
        ],
    },
    {
        "role_type": "support",
        "family": "配套设备",
        "series_name": "整流变压器",
        "code": "rectifier_transformer",
        "vendor": "标准产品",
        "description": "LCI 主回路配套整流变压器。",
        "voltage_levels": ["6kV", "10kV"],
        "min_power_kw": 2000,
        "max_power_kw": 20000,
        "topology": "隔离降压",
        "applicable_motors": ["同步电机"],
        "applicable_loads": ["鼓风机", "压缩机", "磨机"],
        "communication_protocols": [],
        "io_allocation": {},
        "protection_features": ["绕组温升监测"],
        "preferred_scenarios": ["LCI 配套"],
        "default_chapters": ["主要设备技术参数", "供货范围与配置清单"],
        "standard_configs": [
            {
                "config_name": "标准配置",
                "components": [],
                "applicable_scenarios": ["LCI 主回路配套"],
                "description": "标准整流变压器配置。",
            }
        ],
        "constraints": [
            {"constraint_type": "electrical", "condition": "与主驱动容量匹配", "action": "需按主回路容量校核变比和容量。", "severity": "blocking"},
        ],
    },
    {
        "role_type": "support",
        "family": "配套设备",
        "series_name": "励磁控制柜",
        "code": "excitation_cabinet",
        "vendor": "标准产品",
        "description": "同步电机专用励磁控制单元。",
        "voltage_levels": ["6kV", "10kV"],
        "min_power_kw": 2000,
        "max_power_kw": 20000,
        "topology": "同步励磁",
        "applicable_motors": ["同步电机"],
        "applicable_loads": ["鼓风机", "压缩机", "磨机"],
        "communication_protocols": ["硬接点"],
        "io_allocation": {"DI": 4, "DO": 4},
        "protection_features": ["失步检测", "励磁异常告警"],
        "preferred_scenarios": ["同步电机配套"],
        "default_chapters": ["启动与同步切换控制", "主要设备技术参数"],
        "standard_configs": [
            {
                "config_name": "同步电机配套",
                "components": [],
                "applicable_scenarios": ["同步电机"],
                "description": "同步电机励磁控制标准配置。",
            }
        ],
        "constraints": [
            {"constraint_type": "control", "condition": "同步电机", "action": "需明确励磁投入、切除和同步切换时序。", "severity": "warning"},
        ],
    },
    {
        "role_type": "support",
        "family": "配套设备",
        "series_name": "旁路切换柜",
        "code": "bypass_cabinet",
        "vendor": "标准产品",
        "description": "主驱动旁路或工频切换专用柜。",
        "voltage_levels": ["6kV", "10kV"],
        "min_power_kw": 500,
        "max_power_kw": 20000,
        "topology": "工频旁路",
        "applicable_motors": ["异步电机", "同步电机"],
        "applicable_loads": ["鼓风机", "风机", "泵", "压缩机"],
        "communication_protocols": ["硬接点"],
        "io_allocation": {"DI": 2, "DO": 2},
        "protection_features": ["切换闭锁", "机械电气双重互锁"],
        "preferred_scenarios": ["工频旁路", "不停机检修"],
        "default_chapters": ["启动与同步切换控制", "供货范围与配置清单"],
        "standard_configs": [
            {
                "config_name": "旁路配置",
                "components": [],
                "applicable_scenarios": ["工频旁路运行", "不停机切换"],
                "description": "旁路切换柜标准配置。",
            }
        ],
        "constraints": [
            {"constraint_type": "control", "condition": "存在旁路切换", "action": "必须明确切换条件、闭锁逻辑和操作票。", "severity": "blocking"},
        ],
    },
]
